version: '3.8'

services:
  backend:
    build: ./backend
    container_name: ai_tutor_backend
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GEMINI_MODEL=gemini-2.5-flash
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - ./backend/data:/app/data
      - ./backend/chroma_db:/app/chroma_db
    restart: unless-stopped
    networks:
      - ai_tutor_network

  frontend:
    build: ./frontend
    container_name: ai_tutor_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - ai_tutor_network

networks:
  ai_tutor_network:
    driver: bridge
